### PR TITLE
Updates contributing guidelines

### PR DESCRIPTION
**Pull request by iteles**
Updates contributing with:
+ When and how to create a new repo, along with the minimum requirements #29 
+ Contents guide for easier reading #28 
+ Fixes some markdown issues and dead links introduced by commits to the content guide.

### CODE REVIEW

**Comment by nelsonic** [comment]
@iteles is this PR `awaiting-review` or have you assigned it to me so I can `continue` working on it? 🤔

**Comment by iteles** [comment]
For review please! Sorry, I missed that line. I only assign when ready for review.

**Comment by nelsonic** [comment]
Right ... we _really_ need to get @dwylbot to apply the `awaiting-review` when a PR is assigned ...
https://github.com/dwyl/dwylbot/issues/62

**Comment by iteles** [comment]
dwylbot hadn't been enabled for this repo yet. Enabled now.

**Review by nelsonic — APPROVED** [review]
@iteles looks great! 🎉

**Pull request merged**
