### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by NE-SmallTown**

### CODE REVIEW

**Comment by NE-SmallTown** [comment]
BTW,this repo is very very helpful and friendly,but I think maybe we can divide the contents into more small pieces and just offer the "table of contents" in README.So everyone could pick the section which they are interested in rather than scroll back and forth,that would be a little fatigued.

On the other hand,we can shrink some pics such as [Thank you](https://github.com/NE-SmallTown/contributing#step-3-submit-the-new-issue),[what to do while](https://github.com/NE-SmallTown/contributing#step-3-submit-the-new-issue).Maybe `400px` or `500px` would be better?

**Comment by nelsonic** [comment]
@NE-SmallTown thanks very much for the feedback! we _really_ appreciated it when people _make_ the time to read this. our "_very soon_" plan is actually to re-org this doc and then make a 5 minute video of it! 😮  which we expect will be _effortless_ for people to watch. 😉

**Review by nelsonic — APPROVED** [review]
@NE-SmallTown thank you _so much_ for _making_ time to fix these typos. 😍  🎉  ⭐️

**Comment by NE-SmallTown** [comment]
You're welcome.I think dwyl is a very good organization,hope to make it better together :smiley:

**Pull request merged**
