### PR TITLE
correcting 'addapted' spelling mistake

### PR DESCRIPTION
**Pull request by Jbarget**
- corrects spelling mistake: addapted --> adapted

### CODE REVIEW

**Review by iteles — APPROVED** [review]
Thanks @jbarget, good catch! (also, thank you for reading the guide 🙏 )

**Review by nelsonic — APPROVED** [review]
@Jbarget thanks for fixing. ❤️ 
do you know if there's a _decent_ spell checker Atom Plugin? 🤔

**Comment by Jbarget** [comment]
no problemo, i havent actually used one but im sure there will be :)
`spell-check` looks well tried

**Comment by nelsonic** [comment]
@markwilliamfirth please _merge_ once reviewed. thanks. 👍

**Comment by nelsonic** [comment]
Given that this is a typo fix not a major change I'm merging. 👍

**Pull request merged**
